; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Button, x7 y18 w161 h70, 시작
Gui Add, Button, x8 y96 w161 h70, 끝

Gui Show, w177 h174, Window
Return

GuiEscape:
GuiClose:
    ExitApp
