; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Menu FileMenu, Add, &Open...`tCtrl+O, MenuHandler
Menu MenuBar, Add, &File, :FileMenu
Menu HelpMenu, Add, &Info`tF1, MenuHandler
Menu MenuBar, Add, &Help, :HelpMenu
Gui Menu, MenuBar

Gui Add, Picture, x8 y16 w215 h34, C:\Users\bluelion\Desktop\Download\AHK\yslogo.png
Gui Add, Text, x8 y72 w73 h23 +0x200 +Right , Student No
Gui Add, Text, x16 y104 w63 h23 +0x200 +Right , Name
Gui Add, Edit, x88 y72 w135 h23
Gui Add, Edit, x87 y104 w136 h21
Gui Add, Button, x8 y360 w80 h23, Save
Gui Add, Button, x144 y360 w80 h23, Cancel
Gui Add, ComboBox, x9 y136 w214, What is your hobby?||Reading books|Playing the piano
Gui Add, Slider, x8 y216 w216 h29, 50
Gui Add, Radio, x8 y280 w83 h23, Satisfied
Gui Add, Radio, x136 y280 w88 h24, Not really
Gui Add, Text, x9 y249 w217 h23 +0x200 +Center, Are you satisfied with your school life?
Gui Add, CheckBox, x104 y328 w120 h23, I read everything.
Gui Add, Text, x8 y168 w216 h23 +0x200 +Center, Are you happy? Show me the number.
Gui Add, Text, x56 y192 w120 h23 +0x200 +Center, Text

Gui Show, w232 h400, YS Informatics
Return

MenuHandler:
Return

GuiEscape:
GuiClose:
    ExitApp
