/* ################################################################
 * 영신여자고등학교 2학년 00반 00번  김 준 오
 * 1. 프로그램명: 스마트 계산기
 * 2. 프로그램 설명: 스마트하게 세상 모든 문제를 풀어주는 계산기
 * 3. 프로그램 제작 목적:
 * 4. 향후 프로그램 업그레이드 계획
 * 5. 제작일자: 2022년 4월 4일 월요일
 * 6. 파일명: 20000_김준오_20220411_스마트계산기.ahk
 * ################################################################
 */

; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

/*
영신여자고등학교 정보 수업
오토핫키를 이용한 GUI 설계 및 간단한 프로그램 제작
2022월 4월 10일 제작
*/

;[글자 폰트 설정]
Gui Font, s9, Segoe UI

;[메뉴바 설정]
Menu FileMenu, Add, &Open...`tCtrl+O, MenuHandler
Menu MenuBar, Add, &File, :FileMenu
Menu HelpMenu, Add, &Info`tF1, MenuHandler
Menu MenuBar, Add, &Help, :HelpMenu
Gui Menu, MenuBar

;[학교 로고]
Gui Add, Picture, x8 y16 w215 h34, C:\Users\Administrator\Desktop\정보 수업\autohotkey_git\yslogo.png

;[학번]
Gui Add, Text, x8 y72 w73 h23 +0x200 +Right , Student_No
Gui Add, Edit, x88 y72 w135 h23 vStdNo

;[성명]
Gui Add, Text, x16 y104 w63 h23 +0x200 +Right , Std_Name
Gui Add, Edit, x87 y104 w136 h21 vStdName

;[취미]
Gui Add, ComboBox, x9 y136 w214 vCB, What is your hobby?||Reading books|Playing the piano

;[행복한 정도]
Gui Add, Text, x8 y168 w216 h23 +0x200 +Center, Are you happy? Show me the number. ;[슬라이더] 슬라이더를 설명하는 부분
Gui Add, Slider, x8 y216 w216 h29 Tickinterval10 gSlider1 altsubmit vSlider1, 50 ;[슬라이더] 행복의 정도를 표시하는 슬라이더
Gui Add, Text, x56 y192 w120 h23 +0x200 +Center vNslider, Happyness level: ;[슬라이더] 행복의 정도를 표시하는 슬라이더에서 보낸 값을 표시하는 부분

;[학교생활 만족]
Gui Add, Text, x9 y249 w217 h23 +0x200 +Center, Are you satisfied with your school life?
Gui Add, Radio, x15 y280 w83 h23 vYes, Satisfied
Gui Add, Radio, x136 y280 w88 h24 vNo, Not really

;[내용을 모두 읽었는지 확인]
Gui Add, CheckBox, x104 y328 w120 h23 vRead, I read everything.

;[저장과 취소 버튼]
Gui Add, Button, x8 y360 w80 h23, Save
Gui Add, Button, x144 y360 w80 h23, Cancel

;[프로그램을 사용자에게 보이기]
Gui Show, w232 h400, YS School
Gui, Submit, NoHide
Return


;####################
;세부 설정하는 부분
;####################



; 저장 버튼을 누르면 실행되는 코드
ButtonSave:
Gui, Submit, NoHide
{

if(Yes = 1)
{
    Satisfaction = Satisfied
}else{
    Satisfaction = Not satisfied
}

if(Read = 1)
{
    done = Done
}else
{
    done = unchecked
}


    MsgBox `nStd ID_No: %StdNo%`n Std_Name: %stdName%`n Hobby: %CB%`n My Happyness level: %Slider1%`n Satisfaction: %Satisfaction%`n Everything: %done%
}
Return

; 취소 버튼을 누르면 실행되는 코드
ButtonCancel:
{
	ExitApp
}
return


;행복 상태를 측정하는 슬라이더 값을 TEXT 창에 표시하는 컨트롤 코드
Slider1: 
Gui, Submit, NoHide
GuiControl,, Nslider, My level: %Slider1%
return


; 프로그래 종료와 관련된 코드
MenuHandler:
Return

; 프로그램 종료 창을 누르면 종료하는 코드
GuiEscape:
GuiClose:
    ExitApp
